### ISSUE TITLE
Automatically test script

### ISSUE THREAD

**Issue by SimonLammer** [SimonLammer/anki-persistence#10]
Automatically test the minified script with as many anki clients as possible, to prevent merging when errors exist in some Persistence implementation.

**Comment by SimonLammer** [comment]
[TravisCI GUI testing](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI) might help

**Comment by qwiglydee** [comment]
Are you going to unit-test only the script, or integrated anki interaction?

**Comment by SimonLammer** [comment]
I would test the anki interaction, but I probably won't implement this issue anyway.

**Comment by SimonLammer** [comment]
Could test on ankiweb using phantomjs.
