### ISSUE TITLE
Consider storing several persistent values.

### ISSUE THREAD

**Issue by qwiglydee** [SimonLammer/anki-persistence#19]
An example usecase: storing randomly generated question and answer, and user answer to provide feedback.

With current implementation such usecase require saving an object and move it back and forth for each item access.
Perhaps, using subtree-keys would be more efficient.
And using WebStorage API  (setItem, getItem, removeItem) would be nicer.

**Comment by SimonLammer** [comment]
Will shortly be implemented according to [this webstorage spec](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface).
Additionally, all methods expecting a key may be used without the key, which uses a default one internally.

**Comment by SimonLammer** [comment]
@qwiglydee Can this be successfully closed after merging #26 ?

**Comment by qwiglydee** [comment]
Yes. indeed.
I suppose that those `fooItem` methods are quite sufficient.
