### ISSUE TITLE
Can't persist the number 0

### ISSUE THREAD

**Issue by thebasser123** [SimonLammer/anki-persistence#37]
I'm using the code to remember a random number (index for an array). Every time the number 0 comes up on the front, Persistence.getItem() on the back returns null.

**To Reproduce**
1. Change random number generation on the example's front to Math.floor(Math.random()*2)
2. Try out the card until 0 comes up on the Front.

**Expected behavior**
Persistence.getItem() on the back should return 0 instead of null, when the front executes:
```
number = 0;
Persistence.setItem(number);
```

**Error occurs in these anki clients:**
 - Windows

**Additional context**
I used a simple workaround: generate the random number starting at 1 instead of 0, then substract 1 when retreiving the array element. This works perfectly. Thought I'd mention the problem though.

**Comment by SimonLammer** [comment]
Thanks for the info.

The issue seems to be that 0 has a falsy value in boolean comparisons and thus [`0 || null`](https://github.com/SimonLammer/anki-persistence/blob/master/script.js#L62) returns `null`.

**Comment by SimonLammer** [comment]
@thebasser123 should be fixed in [this version](https://github.com/SimonLammer/anki-persistence/releases/tag/v0.5.3) - please confirm if it really is.
