### ISSUE TITLE
Travis Build Error

### ISSUE THREAD

**Issue by SimonLammer** [SimonLammer/anki-persistence#43]
see https://travis-ci.org/github/SimonLammer/anki-persistence

**Comment by fuzzmz** [comment]
@SimonLammer, can I get this assigned to myself?

**Comment by SimonLammer** [comment]
sure

**Comment by SimonLammer** [comment]
I have only glanced over the error - it seems like the website I used for minimizing the javascript isn't available anymore.

**Comment by fuzzmz** [comment]
@SimonLammer, yes. I'll switch to using the native package installed via npm. See [here](https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler-js/readme.md) for more info on why the JS version of closure-compiler is no longer supported or maintained.

**Comment by SimonLammer** [comment]
```
$ npm install google-closure-compiler:latest

npm ERR! code EINVALIDTAGNAME

npm ERR! Invalid tag name "google-closure-compiler:latest": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2020-10-06T05_49_50_771Z-debug.log

The command "npm install google-closure-compiler:latest" failed and exited with 1 during .
```
