### ISSUE TITLE
Persisting multiple fields for Cloze card templates

### ISSUE THREAD

**Issue by rumDMC** [SimonLammer/anki-persistence#47]
Having an issue persisting fields in a cloze card.
Of note:
The addon I am using to randomize these fields is "[Field Modifier Random Item Fork for 21](https://ankiweb.net/shared/info/1940275457)" 
With said addon, to randomize a field, one simply puts {{random::Field Name}}

That being said, I am not able to persist two fields on a working template.
Field names to persist are:: Shuffle Cloze; Shuffle Text

Current set up is:
**EDIT:
It seems that posting the code here results in parts of it being taken out, so I also attached images of the script in full. Please refer to that before confirming that something is missing from the script**
Front Script:
![Screenshot 2021-02-26 131859](https://user-images.githubusercontent.com/63619599/109339191-491a6b00-7835-11eb-97e3-95f0fbce3db0.png)

Back Script
![Screenshot 2021-02-26 131923](https://user-images.githubusercontent.com/63619599/109339190-4881d480-7835-11eb-9283-06879c1b54e5.png)

**Front:**
<script>
// v0.5.2 - https://github.com/SimonLammer/anki-persistence/blob/62463a7f63e79ce12f7a622a8ca0beb4c1c5d556/script.js
if(void 0===window.Persistence){var _persistenceKey="github.com/SimonLammer/anki-persistence/",_defaultKey="_default";if(window.Persistence_sessionStorage=function(){var e=!1;try{"object"==typeof window.sessionStorage&&(e=!0,this.clear=function(){for(var e=0;e<sessionStorage.length;e++){var t=sessionStorage.key(e);0==t.indexOf(_persistenceKey)&&(sessionStorage.removeItem(t),e--)}},this.setItem=function(e,t){void 0==t&&(t=e,e=_defaultKey),sessionStorage.setItem(_persistenceKey+e,JSON.stringify(t))},this.getItem=function(e){return void 0==e&&(e=_defaultKey),JSON.parse(sessionStorage.getItem(_persistenceKey+e))},this.removeItem=function(e){void 0==e&&(e=_defaultKey),sessionStorage.removeItem(_persistenceKey+e)})}catch(e){}this.isAvailable=function(){return e}},window.Persistence_windowKey=function(e){var t=window[e],i=!1;"object"==typeof t&&(i=!0,this.clear=function(){t[_persistenceKey]={}},this.setItem=function(e,i){void 0==i&&(i=e,e=_defaultKey),t[_persistenceKey][e]=i},this.getItem=function(e){return void 0==e&&(e=_defaultKey),t[_persistenceKey][e]||null},this.removeItem=function(e){void 0==e&&(e=_defaultKey),delete t[_persistenceKey][e]},void 0==t[_persistenceKey]&&this.clear()),this.isAvailable=function(){return i}},window.Persistence=new Persistence_sessionStorage,Persistence.isAvailable()||(window.Persistence=new Persistence_windowKey("py")),!Persistence.isAvailable()){var titleStartIndex=window.location.toString().indexOf("title"),titleContentIndex=window.location.toString().indexOf("main",titleStartIndex);titleStartIndex>0&&titleContentIndex>0&&titleContentIndex-titleStartIndex<10&&(window.Persistence=new Persistence_windowKey("qt"))}}
</script>

{{edit:random:cloze:Shuffle Cloze}}<br>
{{edit:random:Shuffle Text}}<br>
{{#Shuffle Cloze}}{{/Shuffle Cloze}}
{{#Shuffle Text}}{{/Shuffle Text}}

<div id="front"></div>

<script>
if (Persistence.isAvailable()) {
Persistence.clear()
Persistence.setItem('Shuffle Cloze')
Persistence.setItem('Shuffle Text')
}
</script>

**Back**:
<script>
// v0.5.2 - https://github.com/SimonLammer/anki-persistence/blob/62463a7f63e79ce12f7a622a8ca0beb4c1c5d556/script.js
if(void 0===window.Persistence){var _persistenceKey="github.com/SimonLammer/anki-persistence/",_defaultKey="_default";if(window.Persistence_sessionStorage=function(){var e=!1;try{"object"==typeof window.sessionStorage&&(e=!0,this.clear=function(){for(var e=0;e<sessionStorage.length;e++){var t=sessionStorage.key(e);0==t.indexOf(_persistenceKey)&&(sessionStorage.removeItem(t),e--)}},this.setItem=function(e,t){void 0==t&&(t=e,e=_defaultKey),sessionStorage.setItem(_persistenceKey+e,JSON.stringify(t))},this.getItem=function(e){return void 0==e&&(e=_defaultKey),JSON.parse(sessionStorage.getItem(_persistenceKey+e))},this.removeItem=function(e){void 0==e&&(e=_defaultKey),sessionStorage.removeItem(_persistenceKey+e)})}catch(e){}this.isAvailable=function(){return e}},window.Persistence_windowKey=function(e){var t=window[e],i=!1;"object"==typeof t&&(i=!0,this.clear=function(){t[_persistenceKey]={}},this.setItem=function(e,i){void 0==i&&(i=e,e=_defaultKey),t[_persistenceKey][e]=i},this.getItem=function(e){return void 0==e&&(e=_defaultKey),t[_persistenceKey][e]||null},this.removeItem=function(e){void 0==e&&(e=_defaultKey),delete t[_persistenceKey][e]},void 0==t[_persistenceKey]&&this.clear()),this.isAvailable=function(){return i}},window.Persistence=new Persistence_sessionStorage,Persistence.isAvailable()||(window.Persistence=new Persistence_windowKey("py")),!Persistence.isAvailable()){var titleStartIndex=window.location.toString().indexOf("title"),titleContentIndex=window.location.toString().indexOf("main",titleStartIndex);titleStartIndex>0&&titleContentIndex>0&&titleContentIndex-titleStartIndex<10&&(window.Persistence=new Persistence_windowKey("qt"))}}
</script>

{{edit:random:cloze:Shuffle Cloze}}<br>
{{edit:random:Shuffle Text}}<br><br>
{{edit:Extra}}<br><br><br>
 <div style='font-family: Ebrima; font-size: 13px;'>{{Tags}}</div>
{{#Shuffle Cloze}}{{/Shuffle Cloze}}
{{#Shuffle Text}}{{/Shuffle Text}}
{{#Extra}}{{/Extra}}

<div id="back"></div>

<script>
if (Persistence.isAvailable()) {
Persistence.getItem('Shuffle Cloze')
Persistence.getItem('Shuffle Text')
Persistence.clear()
}
</script>

**Comment by SimonLammer** [comment]
You only pass one argument to the `Persistence.setItem` functions, so they are mapped to the internal default key.
To store multiple values, you can specify the keys manually - e.g. `Persistence.setItem("mykey", "myvalue")`.

Seems like cloze cards behave normal with anki persistence.
Here is an example with two random numbers in a cloze card:

Front Template:
```
{{cloze:Text}}

<div id="rng">Random number</div>

<script>// v0.5.3 - https://github.com/SimonLammer/anki-persistence/blob/7107e73086189c190c4d326ef11ebbcded9a08c6/script.js
if(void 0===window.Persistence){var _persistenceKey="github.com/SimonLammer/anki-persistence/",_defaultKey="_default";if(window.Persistence_sessionStorage=function(){var e=!1;try{"object"==typeof window.sessionStorage&&(e=!0,this.clear=function(){for(var e=0;e<sessionStorage.length;e++){var t=sessionStorage.key(e);0==t.indexOf(_persistenceKey)&&(sessionStorage.removeItem(t),e--)}},this.setItem=function(e,t){void 0==t&&(t=e,e=_defaultKey),sessionStorage.setItem(_persistenceKey+e,JSON.stringify(t))},this.getItem=function(e){return void 0==e&&(e=_defaultKey),JSON.parse(sessionStorage.getItem(_persistenceKey+e))},this.removeItem=function(e){void 0==e&&(e=_defaultKey),sessionStorage.removeItem(_persistenceKey+e)})}catch(e){}this.isAvailable=function(){return e}},window.Persistence_windowKey=function(e){var t=window[e],i=!1;"object"==typeof t&&(i=!0,this.clear=function(){t[_persistenceKey]={}},this.setItem=function(e,i){void 0==i&&(i=e,e=_defaultKey),t[_persistenceKey][e]=i},this.getItem=function(e){return void 0==e&&(e=_defaultKey),void 0==t[_persistenceKey][e]?null:t[_persistenceKey][e]},this.removeItem=function(e){void 0==e&&(e=_defaultKey),delete t[_persistenceKey][e]},void 0==t[_persistenceKey]&&this.clear()),this.isAvailable=function(){return i}},window.Persistence=new Persistence_sessionStorage,Persistence.isAvailable()||(window.Persistence=new Persistence_windowKey("py")),!Persistence.isAvailable()){var titleStartIndex=window.location.toString().indexOf("title"),titleContentIndex=window.location.toString().indexOf("main",titleStartIndex);titleStartIndex>0&&titleContentIndex>0&&titleContentIndex-titleStartIndex<10&&(window.Persistence=new Persistence_windowKey("qt"))}}

if (Persistence.isAvailable()) {
  Persistence.clear();
  var r1 = Math.random();
  var r2 = Math.random();
  var field = "{{Text}}";
  Persistence.setItem("r1", r1);
  Persistence.setItem("r2", r2);
  Persistence.setItem("field", field);
  document.getElementById("rng").innerHTML = r1 + " " + r2 + " " + field;
}
</script>
```

Back Template:
```
{{cloze:Text}}

<div id="rng">Random number</div>

<script>// v0.5.3 - https://github.com/SimonLammer/anki-persistence/blob/7107e73086189c190c4d326ef11ebbcded9a08c6/script.js
if(void 0===window.Persistence){var _persistenceKey="github.com/SimonLammer/anki-persistence/",_defaultKey="_default";if(window.Persistence_sessionStorage=function(){var e=!1;try{"object"==typeof window.sessionStorage&&(e=!0,this.clear=function(){for(var e=0;e<sessionStorage.length;e++){var t=sessionStorage.key(e);0==t.indexOf(_persistenceKey)&&(sessionStorage.removeItem(t),e--)}},this.setItem=function(e,t){void 0==t&&(t=e,e=_defaultKey),sessionStorage.setItem(_persistenceKey+e,JSON.stringify(t))},this.getItem=function(e){return void 0==e&&(e=_defaultKey),JSON.parse(sessionStorage.getItem(_persistenceKey+e))},this.removeItem=function(e){void 0==e&&(e=_defaultKey),sessionStorage.removeItem(_persistenceKey+e)})}catch(e){}this.isAvailable=function(){return e}},window.Persistence_windowKey=function(e){var t=window[e],i=!1;"object"==typeof t&&(i=!0,this.clear=function(){t[_persistenceKey]={}},this.setItem=function(e,i){void 0==i&&(i=e,e=_defaultKey),t[_persistenceKey][e]=i},this.getItem=function(e){return void 0==e&&(e=_defaultKey),void 0==t[_persistenceKey][e]?null:t[_persistenceKey][e]},this.removeItem=function(e){void 0==e&&(e=_defaultKey),delete t[_persistenceKey][e]},void 0==t[_persistenceKey]&&this.clear()),this.isAvailable=function(){return i}},window.Persistence=new Persistence_sessionStorage,Persistence.isAvailable()||(window.Persistence=new Persistence_windowKey("py")),!Persistence.isAvailable()){var titleStartIndex=window.location.toString().indexOf("title"),titleContentIndex=window.location.toString().indexOf("main",titleStartIndex);titleStartIndex>0&&titleContentIndex>0&&titleContentIndex-titleStartIndex<10&&(window.Persistence=new Persistence_windowKey("qt"))}}

if (Persistence.isAvailable()) {
  var r1 = Persistence.getItem("r1");
  var r2 = Persistence.getItem("r2");
  var field = Persistence.getItem("field");
  document.getElementById("rng").innerHTML = r1 + " " + r2 + " " + field;
}

</script>
```

If you want to persist a field from the note you can store it in a javascript variable like so: `var field = "{{Text}}";`.
I havn't tried it with that the field randomization addon, but I'd expect it to work just fine - don't hesitate to open another issue if it doesn't.

---

![image](https://user-images.githubusercontent.com/11311769/109349153-c8c82a00-7875-11eb-8e1a-0f3f15ea2d3b.png)
![image](https://user-images.githubusercontent.com/11311769/109349175-d1206500-7875-11eb-92f7-66307b2b6053.png)
![image](https://user-images.githubusercontent.com/11311769/109349189-d7164600-7875-11eb-8e96-0ae8259fa2ff.png)

**Comment by rumDMC** [comment]
Hey, sent you a message on reddit, but just following up here as well.
First off, thanks for your help. I'm finally able to persist items from front to back, and you're right, it works fine with that randomizer addon.

The limitation I'm running up against with Persistence is that if I persist a cloze field from the front to the back, it displays it exactly how it showed up on the front, i.e. with the words still clozed out. What I've been trying to do is get it to persist to the back but show the answer.

To give an example to make it more clear:
I use the radomizer addon to alternate which of these two phrases are displayed ->
Phrase 1= {{c1::Apples}} are {{c2::sweet}} {{c1::Limes}} are {{c2::sour}}
Phrase 2= {{c1::Limes}} are {{c2::sour}} {{c1::Apples}} are {{c2::sweet}}

So that addon will randomly choose whether I see phrase 1 or phrase 2.
But when I flip to the back side it will run the randomizer again and I may get the other phrase instead of the one the front displayed.

When I put in anki persistence, it solves this issue. I get the same phrase shown on the front and the back. HOWEVER, it does not show the answer to the cloze.
Example -> Front - {{...}} are sweet {{...}} are sour
Back - {{...}} are sweet {{...}} are sour.

The phrase selection is maintained but the cloze answer is not displayed. I dont know if there's a way around this and I don't want to make another GitHub issue since I feel like it is pretty niche. If you do decide you want to look into it, I'll post a shot of what my card template is so we can be on the same page.


Either way, thanks for your help previously. I'm super new to this stuff but I was able to figure out how to use Persistence thanks to you!

**Comment by hgiesel** [comment]
Hey @rumDMC
You must know that the replacement of clozes with either hints or answers is done before anki-persistence can get ahold of them.
So you save the question version inside of anki-persistence, and then replace it for the back side.

What you would need to do instead is generate a randomized sequence for it (e.g. you have two items, so `0` and `1`) , save this sequence with anki-persistence, and then apply it when showing front/back. You see this is not trivial. There are some people, who tried to implement this, [including me](https://github.com/hgiesel/closet).

**Comment by SimonLammer** [comment]
> You must know that the replacement of clozes with either hints or answers is done before anki-persistence can get ahold of them.

Theoretically one could work around that fact by storing the field value inside a JS variable and replacing the `{{c1:...}}` stuff manually. However, this doesn't feel like a good idea.

> What you would need to do instead is generate a randomized sequence for it (e.g. you have two items, so 0 and 1) , save this sequence with anki-persistence, and then apply this randomized sequence when showing front/back.

I agree, manually randomly choosing one of the fields instead of using the randomization addon is probably the easier and cleaner way to achieve the desired result.

> You see this is not trivial.

Not terribly difficult either; should be doable in a few of hours ;)

**Comment by rumDMC** [comment]
Okay, you guys have helped a ton. I have it set up to randomly display one of two items (0 or 1), but I do not know how to set its selection to persist to the back and show the clozed phrase.
With the way the template is set right now, I only get the word 'inline' printed on the back side. 
Here's where I am:
![image](https://user-images.githubusercontent.com/63619599/109441624-b7148d00-7a03-11eb-9e6f-8f6ee6833c8a.png)



Any ideas as to what to change? I assume the **var text =**   is what is causing the issue, but I dont know how to persist the field from front to back and allow it to show the clozed phrase any other way?

**Comment by SimonLammer** [comment]
@rumDMC Try changing that line to `var text = document.getElementById(Math.floor(Math.random() * 2)).innerHTML;`.

**Comment by rumDMC** [comment]
Step in the right direction! But the back isn't displaying the clozed words, its just repeating what the front shows. 

If I put "var text = document.getElementById(Math.floor(Math.random() * 2)).innerHTML;" into the persist script in the back then it DOES show the clozed values, but it randomizes which phrase is being shown again rather than maintaining it from the front.
![image](https://user-images.githubusercontent.com/63619599/109488637-d2a78400-7a53-11eb-8b99-b8f6eef06bb3.png)

(If I dont put the highlighted phrase where it is in the script then the cloze stays blocked out on the back)



Also, @hgiesel I actually have closet and have been exploring what all it can do for a few days now. It's seriously amazing. I havent seen a way for it to do what Im trying to do here though, which is essentially [[mix:cloze phrase1 | cloze phrase 2]].

**Comment by SimonLammer** [comment]
My bad, I went back to the old problem.

Something like this should work:
```
var texts = ["{{cloze:Cloze Phrase 1}}", "{{cloze:Cloze Phrase 2}}"];
var index = 0;
if (Persistence.isAvailable()){
// use persistence to persist `index` (on the frontside); or override `index` with the persisted value (on the backside)
}
document.getElementById('text').innerHTML = texts[index];
```

**Comment by rumDMC** [comment]
LETS GOOOOOOOOOO

I got it! You're probably going to laugh at how I did it (there's got to be a much more succinct way), but I got it to work and I'm happy haha

Screenshots of the template:
![image](https://user-images.githubusercontent.com/63619599/109563227-7cffc580-7aad-11eb-8078-2b914e213943.png)
![image](https://user-images.githubusercontent.com/63619599/109563320-9b65c100-7aad-11eb-9553-fe3382df999c.png)



You can officially mark this as closed!!!

**Comment by rumDMC** [comment]
AAAANNND I broke it....

Invalid HTML on card: SyntaxError: Unexpected identifier
SyntaxError: Unexpected identifier
at eval ()
at http://127.0.0.1:60031/_anki/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:60031/_anki/jquery.js:2:2662)
at Ha (http://127.0.0.1:60031/_anki/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:60031/_anki/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:60031/_anki/jquery.js:3:24070)
at Y (http://127.0.0.1:60031/_anki/jquery.js:3:4515)
at n.fn.init.html (http://127.0.0.1:60031/_anki/jquery.js:3:23660)
at HTMLDivElement. (http://127.0.0.1:60031/_anki/reviewer.js:33:16)
at HTMLDivElement.d.complete (http://127.0.0.1:60031/_anki/jquery.js:4:6203)


Any advice?

**Comment by hgiesel** [comment]
Use backquotes instead of `"` for your texts.

**Comment by rumDMC** [comment]
Got it! That's something I'm actually capable of doing ha

**Comment by SimonLammer** [comment]
@rumDMC I'm glad you got it working.

A few more things that you might want to clean up:

1. `var index = Math.floor(Math.random() * 2)` does the exact same thing as the 7-line assignment you made in [the front screenshot](https://user-images.githubusercontent.com/63619599/109563227-7cffc580-7aad-11eb-8078-2b914e213943.png), but is shorter.
2. The `innerHTML` attributes of your elements are not being set if persistence is not available (which is the case in most preview windows). I think it'd be better to set `var index = 0;` initially, then only randomize the index if `Persistence.isAvailable()` and finally set the `innerHTML` attributes (without checking for persistence availability since the index will always be 0 if it's not available) similar to [how the example works](https://github.com/SimonLammer/anki-persistence#setup).
