### ISSUE TITLE
I reopen deck, the value is not persisted.

### ISSUE THREAD

**Issue by okerivy** [SimonLammer/anki-persistence#52]
**Describe the bug**
Hello, I want to save a value locally, such as volume.
But there seems to be no way to keep it now. It can only be retained when switching from card to card.
If **I reopen deck, this value disappears. The value is not persisted.**

Complete code
<details>
<summary>Front</summary>

```javascript
{{Front}}
  <button  onclick="changeVoice(this);" id="btn_id_voice"
           style="display:display;">hello btn</button>

<div id="front"></div>
  

<script>

var number = 0.4;                 // Default to 0.4.
if (Persistence.isAvailable()) {  // Check whether Persistence works on the client.
  number = Persistence.getItem("number"); // Retrieve a previously stored number and override the default. (In case this is executed on the backside as well by {{FrontSide}})
  if (number == null) {           // If there was no number stored previously:
    number = Math.random();       //   1. Create a random number and override the default.
    Persistence.setItem("number", number);  //   2. Store that number
  }
}
window.front.appendChild(document.createTextNode(number)); // Print the number.

var voice = 1.1;               
if (Persistence.isAvailable()) {  
  voice = Persistence.getItem("voiceNum"); 
  if (voice == null) {          
    voice = 1.5;       //   Default to 1.5
    Persistence.setItem("voiceNum", voice); 
  }
}
var btn_id_voice = document.getElementById("btn_id_voice");
btn_id_voice.innerHTML = `init ${voice} `;

function changeVoice(btnId) {
  var voice = 0.9;               
  if (Persistence.isAvailable()) { 
    voice = Persistence.getItem("voiceNum");
    // if (number == null) {          
    voice = Math.random();       //   1. Create a random number and override the default.
    Persistence.setItem("voiceNum", voice);  //   2. Store that number
    // }
  }

  btnId.innerHTML = `my voice ${voice}`;
}

</script>
```
</details>

<details>
<summary>Back</summary>

```javascript

<script>

var number = 0.4;                 // Default to 0.4.
if (Persistence.isAvailable()) {  // Check whether Persistence works on the client.
  number = Persistence.getItem("number"); // Retrieve the previously stored number and override the default.
  Persistence.removeItem("number");            // Clear the storage, so a new random number will be created on the next card.
}
window.back.appendChild(document.createTextNode(number)); // Print the number.


</script>
```

</details>

**To Reproduce**

On MAC Anki 2.1.49:
1. Open the deck, click the button, and card A will generate a volume value. When switching to card B, this volume will remain.
2. But if you **_return to the home page and reopen the deck,_** **the volume value is gone,** and the default value<1.5> is restored.
<img src="https://user-images.githubusercontent.com/4578474/146727720-52c60d16-58fd-4ca8-a10a-f3be1868f0d2.png" width="400"   />

On ios
1. Open the deck, click the button and card A will generate a volume value. When switching to card B, this volume will remain.
2. Return to the home page and reopen the deck, then the volume value will also be the last value.
3. But if i r**estart the anki app, this value disappears.**

**Expected behavior**

I hope to keep this value locally. This value will remain regardless of whether you reopen the deck or restart the app.

I wonder if it can be achieved?  If it does not work, I want to keep this value when I reopen deck on the MAC。

**Screenshots**

**Error occurs in these anki clients:**
 - iOS
 - Mac (2.1)

**Additional context**
This is my anki template, you can download it and check it out. thanks

[anki-persistence-voice.apkg.zip](https://github.com/SimonLammer/anki-persistence/files/7743212/anki-persistence-voice.apkg.zip)

**Comment by SimonLammer** [comment]
anki-persistence only persists values from frontside to backside of a card during review.
If you want to keep a value across restarts I suppose you could store it in the note from which the card is generated.
