### ISSUE TITLE
key pairs don't seem to work on ankidroid

### ISSUE THREAD

**Issue by boydkelly** [SimonLammer/anki-persistence#53]
**Describe the bug**
default variable persists to card back, but key value pairs dont.

**To Reproduce**
1. Import anki-persistence-test.apkg on android device
2. Click on Anki persistence test
3. Click on Show answer

Random number will be displayed the same on card front and back
window objects are displayed on card front
**No persistent window objects are displayed on card back**

**Expected behavior**
Persistent window objects are displayed on card back

**Screenshots**

**Error occurs in these anki clients:**
 - Android

**Additional context**

**Comment by SimonLammer** [comment]
Thank you for leaving a bug report.

Alas, I could not replicate the bug.
![image](https://user-images.githubusercontent.com/11311769/169464483-b9e7fd77-b0c9-4a56-a58d-93012e80a059.png)
![image](https://user-images.githubusercontent.com/11311769/169464512-23742fa6-4bdc-45c2-8a78-89f8d194e44c.png)

As you can see the number is 0.9163978499011356 on both card sides.

What are your Android and AnkiDroid versions?
What text are you shown below the number on the frontside?
